### ISSUE TITLE
Convert Collection of Hashes to Array of String

### ISSUE THREAD

**Issue by sushengloong** [nesquena/rabl#133]
Hi,

I have a collection of hashes which I would like to render as a simple array of string values. For example, instead of 

<pre>
[{"name" => "Ruby"}, {"name" => "Python"}, {"name" => "Java"}]
</pre>

I want it to be

<pre>
["Ruby", "Python", "Java"]
</pre>

May I know if this is achievable in rabl? Thank you.

Sheng-Loong

**Comment by rk-panchal** [comment]
id =  @order.products[0]['id']          
          parts = Spree::Product.find_by_id(id).parts 
          
       

              parts.each  do |ap| 

                node(:product_id) {  ap.product_id }
                node(:sku) {  ap.sku }
                node(:name) {  ap.name }                       
              
              end unless parts.nil? 

its give me only last reorrds  from parts 
but parts have more than one records

how can i show all records of  parts.



Please share any suggestionn
