### ISSUE TITLE
Combining collections?

### ISSUE THREAD

**Issue by neezer** [nesquena/rabl#140]
How can I combine collections? I want to do something like this:

```
object @green_stuff
object @red_stuff
```

So I can get an output like this:

```
{ [ { "green_thing" : { ... } }, { "red_thing": { ... } } ] }
```

... but sequential `object` calls only seem to return the last one, so my output is always like:

```
{ [ { "red_thing" : { ... } } ] }
```

How can I combine these two collections into one JSON array with RABL?

NOTE: I do _not_ want plural root elements, which I know I can get via `child` and `object false`.

**Comment by nikhilvallishayee** [comment]
Issue is still open. I have two collections that need to be passed as a single json array. But the attributes being sent and nodes being created for objects of one array are different from that of the other. How is that case handled?
