### ISSUE TITLE
Rendering an array of hashes

### ISSUE THREAD

**Issue by simonc** [nesquena/rabl#141]
I would like to render an array of objects like this:

``` ruby
[{ name: "obj1", data: [1,2,3] }, { name: "obj2", data: [2,3,4] }]
```

And obtain something like this:

```
{"stats": [
    {"name": "obj1", "data": [1,2,3]},
    {"name": "obj2", "data": [2,3,4]}
]}
```

But the closest I could get looked like this:

```
{"stats":[
    {"stat": {"name": "obj1", "data": [1,2,3]}},
    {"stat": {"name": "obj2", "data": [2,3,4]}}
]}
```

How can I get rid of the useless "stat" level ?
Thanks

**Comment by chitrank-samaiya** [comment]
+1

**Comment by Zprotonlabs** [comment]
class alum
has_many images

image has attribute status(0,1)

i want to show only images having status 1 against all albums

**Comment by Zprotonlabs** [comment]
{
  "photographer": {
    "albums": [
      {
        "id": 1,
        "name": "Album 1",
        "description": "wOW",
        "images": [
          {
            "image": {
              "image_id": 3,
              "url": "/system/images/images/000/000/003/original/packages.png?1472735728",
              "is_liked": false
            }
          },
          {
            "image": {
              "image_id": 2,
              "url": "/system/images/images/000/000/002/original/packages.png?1472712813",
              "is_liked": false
            }
          }
        ]
      }
    ],
    "is_followed": false,
    "url": "user-avatar.png",
    "rating": null,
    "badge": null,
    "number_of_clients": 4,
    "number_of_follows": 0,
    "number_of_likes": 0,
    "is_connected": false
  },
  "status": 1,
  "message": "Profile found successfully!"
}


but it shows all images

**Comment by bcarradini** [comment]
I had an object that included, among other things, an array of "giver" objects that might or might not be empty. Here's what I did:
```
object self

if !self.recent_givers.empty?
  node(:givers) do
    self.recent_givers.map do |giver|
      {:id => giver.id, :photo_url => giver.photo_url}
    end
  end
end
```

This produced the following result, which is what I wanted:
```
    "givers": [
        {
            "id": 386,
            "photo_url": "https://..."
        },
        {
            "id": 918,
            "photo_url": "https://..."
        },
        {
            "id": 341,
            "photo_url": "https://..."
        },
        {
            "id": 868,
            "photo_url": "https://..."
        }
    ],

Oddly, when I initially attempted to use `self.recent_givers.each` to loop through the array, the resulting list of "givers" always included the entire set of attributes belonging to a "giver" object regardless of what I specified inside the loop.
