### ISSUE TITLE
How to remove the root node?

### ISSUE THREAD

**Issue by joel** [nesquena/rabl#15]
I have

```
[{"person":{"id":1,"firstname":"Zaphod","lastname":"BEEBLEBROX","gender":"Mr"}},{"person":{"id":2,"firstname":"Ford","lastname":"PREFECT","gender":"Mr"}}]
```

But i would like

```
[{"id":1,"firstname":"Zaphod","lastname":"BEEBLEBROX","gender":"Mr"},{"id":2,"firstname":"Ford","lastname":"PREFECT","gender":"Mr"}]
```

it's possible ?

I have builder template **index.json.rabl** for People#index controller with

```
attributes :id, :firstname, :lastname, :gender
```

and the collection of objects => @people

**Comment by Mahesh2furdo** [comment]
in config/initializer
create rabl_confir.rb

Rabl.configure do |config|
  config.include_json_root = false
  config.include_child_root = false
end
