### ISSUE TITLE
Allow to add root node

### ISSUE THREAD

**Issue by inkstak** [nesquena/rabl#174]
Hi,

Sometimes, I need to add nodes to root when am rendering collections or objects.. and it's always tricky.

Let's take an example. I need to render the following hash, to be able to paginate my data :

```
{  total: 250,
   page: 3,
   data: [
     { id: 1, name: "Foo", ...},
     { id: 2, name: "Bar", ...}
  ]
}
```

I searched a bit how to get such thing, and i only found the following trick :

```
object false
node(:total) { @items.total_count }
node(:page) { @page }

child(@items => :data) do
  attributes :id, :name
end
```

Is it possible to add a cleaner way ?

```
collection @items => :data

attributes :id, :name

root_node total: @items.total_count
root_node page: @page
```

**Comment by joelpresence** [comment]
Has this been resolved?  I could really use this feature ... :-)

**Comment by coolgeng** [comment]
+1
