### ISSUE TITLE
Using Draper with Rabl

### ISSUE THREAD

**Issue by cmer** [nesquena/rabl#286]
I have the following templates:

```
# autocomplete_suggestions
collection @users
extends "memberships/autocomplete_suggestion"
```

and

```
# autocomplete_suggestion
object UserDecorator.decorate(@user)
attributes :id

node(:name)     { |u| u.full_name }
node(:avatar)   { |u| u.avatar_url }
node(:type)     { |u| u.class.to_s }
node(:location) { |u| u.location || '' }
```

`avatar_url` is defined in my Draper decorator, but I cannot access it from inside the node. Is there a way to wrap my @user object in a decorator from inside Rabl?

**Comment by MaicolBen** [comment]
> So I'll call that a bug that we'll address with the refactor in v1. 

Any update on this? It is bad to map twice (in the controller decorating and in the rabl)
