### ISSUE TITLE
How to invalidate a rabl cache?

### ISSUE THREAD

**Issue by calvinl** [nesquena/rabl#291]
I'd like to invalidate a template cache the moment it's been updated. I've tried to do this with `expire_fragment` using the cache key I specified, but it doesn't seem to work. Is there a method to do this or is only time based cache expiration supported?

**Comment by netwire88** [comment]
Hi @databyte Is the caching still the same with Rails 4? I'm noticing that the cached RABL gets reused even though the underlying model's `updated_at` (Mongoid) has changed via `user.touch`.

**Comment by rfjackson11** [comment]
@netwire88 did you ever figure out an answer to your question? I am having the same problem.

**Comment by databyte** [comment]
@netwire88 and @rfjackson11 - it should still be based on the `cache_key` on the object. It's possible that Mongoid doesn't build a cache_key based on the updated_at (but it should). I'm not as familiar with Mongoid.

I did find [this on SO](http://stackoverflow.com/questions/13851970/rails-cache-name-defaults-to-models-id-rather-than-cache-key)
