### ISSUE TITLE
Easy way to pretty print output?

### ISSUE THREAD

**Issue by barmstrong** [nesquena/rabl#301]
I was wondering if there was an easy way to pretty print the generated json output?  This would be really helpful in development as you are debugging/adding attributes etc.  Thanks!

**Comment by Dorian** [comment]
I made a gist of it: https://gist.github.com/Dorian/756a516e4a3309389d32

**Comment by jimflood** [comment]
This added to `config/initializers/rabl_init.rb` formats datetime in ISO 8601 in case you need to validate against JSON schemas:

    ActiveSupport::TimeWithZone.class_eval do
      alias_method :orig_to_s, :to_s
      def to_s(format = :default)
        format == :default ? iso8601 : orig_to_s(format)
      end
    end
