### ISSUE TITLE
Mongoid _id field returns object instead of String

### ISSUE THREAD

**Issue by sethvargo** [nesquena/rabl#337]
When trying to access the `:_id` field like so:

``` ruby
object @object
attributes :_id, ...
```

the rendered JSON is: 

``` javascript
"id": {
  "$oid": "504f8163a3bbccc81b000007"
},
```

but the rendered JSON when simply calling `to_json` is:

``` javascript
"_id": "504f8163a3bbccc81b000007"
```

I think it's because `to_json` implicitly calls `to_s` on the field, but not 100% sure on that one.

How can I actually return the `object_id` as a string? I really don't want to create an attribute to call `to_s` for each of my models.

**Comment by netwire88** [comment]
If you are using Mongoid 4, which changed how `id` are used using BSON, check out the answer here by updating `mongoid.rb`: http://stackoverflow.com/questions/18646223/ruby-model-output-id-as-object-oid/20813109
