### ISSUE TITLE
Meta nodes for a collection

### ISSUE THREAD

**Issue by jmonteiro** [nesquena/rabl#375]
Hey,

Sorry for using Issues to ask a question, but I couldn't find how to do that neither on issues nor on the wiki:

**How can I create some static (meta) nodes when dealing with a collection?**

For instance, currently I have this code...

```
collection @fruits
attributes :name, :price
```

That generates this JSON:

```
{
  "fruits":
  [
    {
      "fruit":
      {
        "name": "Apple",
        "price": "0.99"
      }
    },
    {
      "fruit":
      {
        "name": "Banana",
        "price": "1.10"
      }
    }
  ]
}
```

But I'd like to generate this:

```
{
  "fruits":
  [
    {
      "fruit":
      {
        "name": "Apple",
        "price": "0.99"
      }
    },
    {
      "fruit":
      {
        "name": "Banana",
        "price": "1.10"
      }
    }
  ],
  "hypermedia":
  [
    "link":
    {
      "rel": "self",
      "href": "/fruits"
    }
  ]
}
```

What should I add to my index.rabl in order to render this "static" node _hypermedia_?

**Comment by jeremyblalock** [comment]
@jmonteiro seems like that link doesn't work anymore. Do you know where it has been moved to?

**Comment by nesquena** [comment]
https://github.com/spree/spree/blob/master/api/app/views/spree/api/v1/countries/index.v1.rabl
