### ISSUE TITLE
How do I print Rabl output to console?

### ISSUE THREAD

**Issue by jwoertink** [nesquena/rabl#388]
I've tried this, but get an error.

``` ruby
@user = User.first
Rabl::Renderer.json(@user, 'api/v1/users/show')

#=> RuntimeError: Cannot find rabl template 'api/v1/users/show' within registered ([]) view paths!
```

Rabl is working fine in my app, but I want to see what the actual templates render, and since I'm using an API, making a request isn't exactly easy. All of my API templates are scoped to a subdomain, and specific request headers, etc... Is there something specific I have to setup before I can render these?

**Comment by ryan2johnson9** [comment]
Thanks a lot! @jwoertink
