### ISSUE TITLE
Rabl::Renderer returns empty object instead of empty array when rendering empty array

### ISSUE THREAD

**Issue by mlibby** [nesquena/rabl#501]
I believe #225 is back

I have a test that passes with rabl-0.7.2 but fails with 0.9.0 because the json returned is `"{}"` instead of `"[]"`

I looked and think I see where the fix was first put in, but I don't see where/how it was broken again.

**Comment by quantumpotato** [comment]
@nesquena @mlibby I run into this, is this related?

http://stackoverflow.com/questions/25525911/empty-collection-with-rabl-rails

**Comment by mlibby** [comment]
They don't seem related. The SO is about calling a missing method, this bug was about incorrect return value. And given the age of this bug, it's probably appropriate to close at this time.

**Comment by quantumpotato** [comment]
Thanks @mlibby . Any idea about this? http://stackoverflow.com/questions/28160985/undefined-method-id-for-class-but-the-console-loads-fine
