### ISSUE TITLE
Without root object, XML representation is wrapped in <hash>

### ISSUE THREAD

**Issue by rwdaigle** [nesquena/rabl#575]
When researching templating libraries one of the things I like to do is see if I can generate output _not_ based on an object or domain model. For instance, to quickly output a string message: `<message>Hi</message>`.

With rabl it would appear the way to do such a thing would be:

``` ruby
object false
node(:message) { 'Hi' }
```

However, the XML output of such a template yields (which contains an arbitrary `hash` wrapper):

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<hash>
  <message>Hi</message>
</hash>
```

Am I approaching this simplest use-case the wrong way? Perhaps rabl doesn't support arbitrary generation of output and requires an object to operate against (please say this isn't the case)?

Either way, it would appear having a `hash` wrapper is a bug.

**Comment by alexagranov** [comment]
Actually, as of today, the above only produces:
```
<string>
  <product>...</product>
</string>
```

But this works:
```
object root: { root: 'products-root' }
node(:product) { ... }
```

giving:
```
<products-root>
  <product>...</product>
</products-root>
