### ISSUE TITLE
Break in production from unexplained error: NoMethodError: undefined method `cache_key' for nil:NilClass

### ISSUE THREAD

**Issue by ajbraus** [nesquena/rabl#595]
I have been using rabl happily with heroku in production, but just starting 2 days ago i started to receive this error:

```
NoMethodError: undefined method `cache_key' for nil:NilClass
```

It is called on the blank line after my attributes call:

```
collection @objects
attributes :id, . . . etc
(CALLED HERE)
```

This is working in dev. I have checked that all these attributes work. I've cloned down my production database and it is still working in dev, just not in heroku.

In general RABL has underdeveloped error reporting. Is there any plan to make it more robust and exact?

**Comment by alexey** [comment]
hello guys, i have very similar isse: http://pastiebin.com/54dc780be35d3

Simple controller with `@users = User.search('term')`
and rabl code: `node(:count) { @users.size }`
