### ISSUE TITLE
Rabl eager loads collection even in the case of a cache hit

### ISSUE THREAD

**Issue by rhomeister** [nesquena/rabl#603]
Rabl seems to eager load the `collection` regardless of whether there is a cache hit or whether the actual collection is needed to generate the cache key.

To reproduce this issue, here is a bare bones controller and view:

Controller: 

```
class UsersController < ApplicationController
    def index
      @users = User.limit(10)
      puts "========end of controller============"
    end
end
```

View: 

```
cache "static cache key", expires_in: 1.day
collection @users
attributes :id
```

Result in logs:

```
========end of controller============
  User Load (0.7ms)  SELECT "users".* FROM "users" LIMIT 10
Cache read: rabl/static cache key//json/0177dcab54eb3e18d7e976b32808d46a ({:expires_in=>1 day})
Cache fetch_hit: rabl/static cache key//json/0177dcab54eb3e18d7e976b32808d46a ({:expires_in=>1 day})
```

Conclusion, even when the cache key is a simple static string and there is a cache hit, the collection of users is still loaded. Obviously, this is a very simple example, but if the collection contains many includes and/or complex queries, this results in a huge performance hit because objects are needlessly loaded into memory.

**Comment by DouweM** [comment]
A month is a pretty good turnaround for a bugfix, right? :)

**Comment by rhomeister** [comment]
Not too shabby ;). Thanks Douwe.

**Comment by rhomeister** [comment]
Hi Douwe,

Would it be possible to release a new version of the gem?

Thanks,
Ruben

**Comment by DouweM** [comment]
@nesquena How about it? :)

**Comment by nesquena** [comment]
@DouweM 0.11.6 released, thanks!
