### ISSUE TITLE
Three quirks in the condition resolver of the builder

### ISSUE THREAD

**Issue by vmeyet** [nesquena/rabl#608]
[Edited]: in fact there is three quirks (plus formatting improvement)

#### Truthy is not true

When using rabl, I found that using a variable that is truthy (instead of being `true`) does not work.
But an example worth a thousand words so here it is:

The following won't be called if @data is let's say `42`, but will if it is `true`
```ruby
node(:myNode, if: @data) { |obj| obj.method(@data) }
```

This is really an odd behaviour in the ruby world.

The source of this can be found here: https://github.com/nesquena/rabl/blob/master/lib/rabl/builder.rb#L217-L231

```ruby
result = options[:if] == true || ...
```

and

```ruby
result = options[:unless] == false || ...
```

In my opinion, this should not be that way.

#### Nil is true

The following will be called if @data is `nil`, but won't if it is `false`
```ruby
node(:myNode, if: @data) { |obj| obj.method(@data) }
```
the code that allows that behaviour is there https://github.com/nesquena/rabl/blob/master/lib/rabl/builder.rb#L218

If `@data` is evaluated to `nil` the block should definitely not be called.

#### `:if` and `:unless` does not take `:if` into account
By parcouring the above code I've also noticed that using both `:if` and `:unless` for the condition would lead to having only the `:unless` condition to be evaluated

The following code will be executed whereas it shouldn't (since the `if` condition is false)

```ruby
node(:myNode, if: false, unless: false) { |obj| obj.method }
```

**Comment by vmeyet** [comment]
made a PR here: https://github.com/nesquena/rabl/pull/609

**Comment by nesquena** [comment]
Merged thanks!
