### ISSUE TITLE
DateTime field not returned in json standard date format

### ISSUE THREAD

**Issue by d3vkit** [nesquena/rabl#610]
This _may_ be something else and not rabl, as it only appeared in an upgrade to Rails4.

Here is the scenario:
I have an api controller using rabl to send back the attributes I want:

``` Ruby
# customers_controller.rb
def customers
  @customers = Customer.where(...)

  respond_with @customers
end
```

``` Ruby
# customers.json.rabl
collection @customers

attributes :id, :name, :salesperson, :billing_start_date
node(:billing_disposition) do |customer|
  { name: customer.inherited_billing_disposition.name }
end
```

However, `billing_start_date` always returns as:
`"billing_start_date\":\"2015-01-13 04:59:59 UTC`

when I think it should look like this:
`billing_start_date\":\"2015-01-13T04:59:59.999Z`

I tried changing the following:
`respond_with @customers` => `render json: @customers.to_json`

to just let rails render without rable with  and the format is correct, so it _seems_ like something is happening with rabl sending back the json. Any ideas?

**Comment by DouweM** [comment]
Could you let me know what versions of Rabl and (if applicable) Oj you are on? And could you show me your configuration (initializer) for both?

Thanks.

**Comment by d3vkit** [comment]
Ah! I had previously upgraded rabl and that didn't fix it, but we didn't have oj in our gemfile. Adding oj has fixed the issue. Thank you for the quick response!

**Comment by timherby** [comment]
We were having the same issue.  Adding OJ fixed it.  Thanks for posting.
