### ISSUE TITLE
Unexpected output when using custom attribute under custom node in collection

### ISSUE THREAD

**Issue by spiman** [nesquena/rabl#629]
I am trying to generate a JSON object response using RABL where the root object has an id property, and a custom child node (an association of the association) with an id property of its own. 

The minimal code needed to reproduce this is the following : 

```
collection @offers
attributes :id
node :shipment do |offer|
    attributes id: offer.listing.shipment_id.to_s 
    #without the to_s call an undefined method to_sym error is thrown
end
```

Output

```
[
  {
     id: 61, 
     shipment: {
         id: "59"
     }
  },
  {
     59: 60,
     id: 60,
     shipment: {
         id: "61"
     }
   },
   {
       59: 59,
       61: 59,
       id: 59,
       shipment: {
           id: "58"
       }
   },
   { 
       58: 58,
       59: 58, 
       61: 58,
       id: 58,
       shipment: {
           id: "57"
       }
   },
  (...)
```

Changing the nested attribute name from id to something else solves the problem.
I'm using v0.11.6 on top of Rails v3.2.16

**Comment by yads** [comment]
We are seeing this too, seems to have been around for a while we are on 0.7

**Comment by yads** [comment]
It seems like the issue is using attributes inside the node block, try changing it to a hash or just use attributes outside the node block.

**Comment by spiman** [comment]
Excuse me for the extreme delay, just closing out any outstanding issues on my part. 
I've switched to hashes too for these cases, after a while it looks more natural.
