### ISSUE TITLE
Key based nodes

### ISSUE THREAD

**Issue by speed-of-light** [nesquena/rabl#633]
Currently I have a rabl file like this:
```
object @Item => false

node :subitems do |item|
  attributes :id, :a
end
```

And it output as expect:
```
{
  subitems: [
    {"id": "1", "a": 'first'},
    {"id": "2", "a": 'second'}
  ]
}
```

But what if I want to make this?
```
{
  subitems: [
    "1": {"a": 'first'},
    "2": {"a": 'second'}
  ]
}
```
Tried to searched around but not found any workable solutions, any ideas? thanks!

**Comment by nesquena** [comment]
```ruby
object @Item => false

node :subitems do |item|
   result = {}
   @item.something.each do |k, v|
       result[k] = v
   end
   # result["1"] = {"a": 'first'}
   result
end
```

and you can produce whatever you want the node to look like by constructing it.

**Comment by speed-of-light** [comment]
Thanks for your help,
I am wondering if there's native way to use `extends` or `partial`?
