### ISSUE TITLE
Ruby 2.3.0 breaks the condition resolver of the builder

### ISSUE THREAD

**Issue by vmeyet** [nesquena/rabl#649]
The fix in #608 is incompatible with ruby 2.3.0.

- [Ruby 2.3.0 introduced `Hash#to_proc`](http://dev.mensfeld.pl/2015/11/ruby-2-3-0-changes-and-features/)

working as follow
```ruby
>> [:a, :b, :c].map(&{a: 2, c: 3}.to_proc)
=> [2, nil, 3]
```

- The fix of the bug #608 introduced the following code:

```ruby
def call_condition_proc(condition, object)
  # This will evaluate lambda, proc & symbol and call it with 1 argument
  return condition.to_proc.call(object) if condition.respond_to?(:to_proc)
  # Else we send directly the object
  condition
end
```

Relying on the duck typing of the existence of `:to_proc` this is now not valid anymore.

since a condition such as
```ruby
@data = { some: 'info' }
node(:myNode, if: @data) { @data }

#> This used to return a node with the hash `{ some: 'info' }`
#> in 2.3.0 this returns nothing
```

Fix can be simply to replace duck typing by type checking:

```ruby
  ...
  return condition.to_proc.call(object) if condition.is_a?(Proc) || condition.is_a?(Symbol)
  ...
```

**Comment by nesquena** [comment]
Thanks, closed by #650, appreciate the help. Will release new version soon

**Comment by shaicoleman** [comment]
Could you please release a new version?

**Comment by cthorner** [comment]
+1 for new release

**Comment by seanculver** [comment]
+1

**Comment by nesquena** [comment]
0.12.0 has been released. Sorry for the delay.

**Comment by seanculver** [comment]
:+1: Thank you!!!!

**Comment by boutil** [comment]
Hi!
When I try to run the associated test, I get a failure.
```
Rabl::Builder #resolve_conditionals asserts that it can use a hash variable on if condition and return true => expected nil, not {:some=>"data"}
```
Shouldn't line 360 be `end.equals({some: 'data'})` instead of `end.equals(nil)`, by comparison about what it is expected when the `if` gets a truthy variable?
