### ISSUE TITLE
ActionView::Template::Error (uninitialized class variable @@cache in Rabl::Digestor) in rails 5.0.0.beta3

### ISSUE THREAD

**Issue by sudhakar377114** [nesquena/rabl#663]
I have enabled the cache using the rake task rails dev:cache in my development.

While caching the object in rabl getting the below error
```
ActionView::Template::Error (uninitialized class variable @@cache in Rabl::Digestor
Did you mean?  catch):

```

**Comment by krzysiek1507** [comment]
@sudhakar377114 this should be fixed with #653
Could you check if the problem still exists with a master?

**Comment by sudhakar377114** [comment]
Thank you @krzysiek1507. Updated the gem ` gem 'rabl', github: "nesquena/rabl" ` works fine.

**Comment by krzysiek1507** [comment]
@sudhakar377114 could you please close issue?

**Comment by databyte** [comment]
Have you guys had luck with caching in Rails 5? Does it work as intended?

**Comment by sudhakar377114** [comment]
@databyte yes, its works fine in rails5 beta3. I used this for object caching in view.
