### ISSUE TITLE
New release due to Rails 5.0.0

### ISSUE THREAD

**Issue by krzysiek1507** [nesquena/rabl#666]
@nesquena could you please release new version due to a release of Rails 5.0.0?

**Comment by krzysiek1507** [comment]
@dgynn

**Comment by krzysiek1507** [comment]
@nesquena ping :)

**Comment by krzysiek1507** [comment]
@nesquena thanks!

**Comment by krzysiek1507** [comment]
Are you going to release a new version today?

**Comment by krzysiek1507** [comment]
Hi @nesquena Any progress?

**Comment by nesquena** [comment]
Released 0.13.0

**Comment by krzysiek1507** [comment]
Thanks!
