### ISSUE TITLE
Variable is nil in Rabl template

### ISSUE THREAD

**Issue by dinomite** [nesquena/rabl#686]
I'm doing something shockingly similar to the [overview section of the readme](https://github.com/nesquena/rabl#overview)…but getting a null value.  Rails app (5.0.0.1) with Rabl (0.13.1) and Devise (4.2.0)

```ruby
# controllers/users_controller.rb
@current_user_id = current_user.id
@recruits = User.where(invited_by_id: @current_user_id)
render 'users/recruits'

# app/views/users/recruits
collection @recruits => :users
attributes :account_name, :account_number, :email, :invitation_sent_at, :invitation_accepted_at, :handle
node(:status) { |recruit| Link.link_status(@current_user_id, recruit.id) }
```

In that `node()` block, `@current_user_id` is always nil.  Certainly this is a Personal Problem™—what am I doing wrong?

**Comment by databyte** [comment]
The instance variable `@current_user_id` should be available everywhere. What does this look like?

```ruby
node(:status_test) { @current_user_id }
```

and then try

```ruby
node(:status_test) { |recruit| puts "#{recruit.id} - #{@current_user_id}" }
```

**Comment by dinomite** [comment]
Thanks for the ideas, but no dice on that.  I did have success explicitly passing it as a local :-/

    @recruits = Rabl.render(users, 'users/recruits', locals: { user_id: current_user.id })
