### ISSUE TITLE
errno eacces

### ISSUE THREAD

**Issue by ditmarbrynza** [nesquena/rabl#692]
Hello, i can't to install rabl. I write gem install rable, then i have error

$ gem install rabl
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_file_s_symlink - (fixtures/ashared/views_rails_3/user
s/phone_number.json.rabl, c:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/r
abl-0.13.1/fixtures/ashared/views_rails_3/users/phone_number.xml.rabl)

i try to setup spree and have problem with rable

Errno::EACCES: Permission denied @ rb_file_s_symlink -
(fixtures/ashared/views_rails_3/users/phone_number.json.rabl,
c:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/rabl-0.13.1/fixtures/ashare
d/views_rails_3/users/phone_number.xml.rabl)
An error occurred while installing rabl (0.13.1), and Bundler cannot continue.
Make sure that `gem install rabl -v '0.13.1'` succeeds before bundling.

In Gemfile:
  spree was resolved to 3.3.0.beta, which depends on
    spree_backend was resolved to 3.3.0.beta, which depends on
      spree_api was resolved to 3.3.0.beta, which depends on
        rabl

how i can solve this error?

**Comment by rakesh1988** [comment]
Complete noob for rails here. how to solve this error?? any help would be appreciated.
