### ISSUE TITLE
Cache digesting errors when using "extends"

### ISSUE THREAD

**Issue by zhengpd** [nesquena/rabl#700]
I saw some digesting errors when using "extends" in the rabl template:

```
'foo/bar' file doesn't exist, so no dependencies
Couldn't find template for digesting: foo/bar
```

The template is like:

```ruby
cache [I18n.locale, root_object]
child :something do
  extends 'foo/bar' # full path is foo/bar.rabl, not a partial like foo/_bar.rabl
end
```

After some research I believe this is caused by how ActionView::Digestor build the dependency tree:

```ruby
# https://github.com/rails/rails/blob/a8ebd48559bea8893aa299f9e27758da0807ef24/actionview/lib/action_view/digestor.rb#L61
def tree(name, finder, partial = false, seen = {})
  ...
  deps = DependencyTracker.find_dependencies(name, template, finder.view_paths)
  deps.uniq { |n| n.gsub(%r|/_|, "/") }.each do |dep_file|
       node.children << tree(dep_file, finder, true, seen)
   end
  ...
end
```

Look the `node.children << tree(dep_file, finder, true, seen)` here. It treats every dependency it found in template as partial, so it tries to find the partial file as `foo/_bar` in my example, not `foo/bar` as expected. I override the `tree` method as following for quick fix:

```ruby
deps.uniq { |n| n.gsub(%r|/_|, "/") }.each do |dep_file|
  # all rabl files under foo/ are treated as non-partials
  partial = dep_file.exclude?('foo/')
  node.children << tree(dep_file, finder, partial, seen)
end
```

However I wonder there's more elegant way other than this to avoid digesting errors.

**Comment by jvalentino90** [comment]
hello @ericbeansmile, I've run into the same problem. Where and how have you overriden the tree method? thanks!

**Comment by zhengpd** [comment]
Closing stale issue.
