### ISSUE TITLE
Drop riot? Unmaintained, broken on Ruby 2.5.

### ISSUE THREAD

**Issue by FauxFaux** [nesquena/rabl#705]
Please consider porting the tests to something that's not `riot`. `riot` hasn't seen a commit or release in four years, and fails to build with current Ruby.

`rabl` is the only user of `riot` I can find.

Can we let it die?

**Comment by swordfish444** [comment]
@FauxFaux Unrelated, but were you able to get RABL working on ruby 2.5? I've been unsuccessful with our upgrade to Rails 5.1.4 with ruby 2.5.

**Comment by FauxFaux** [comment]
It currently builds and passes its tests on [Debian's 2.5 CI infrastructure](https://gist.github.com/FauxFaux/aa897aa624f7b7f2677489a160a44e33). I haven't actually tried to use the result, though, no.

**Comment by tagliala** [comment]
Hello, I think that this can be closed
