### ISSUE TITLE
Formatting the XML format

### ISSUE THREAD

**Issue by claudiolassala** [nesquena/rabl#74]
Hi all,

Is there anyway to customize the shape of the XML being produced? For instance, I need to produce an output that uses XML attributes, instead of elements. In other words, this...

`<auth status="FAILED"
    errorcode="UNKNOWN_LOGIN"
    errormessage=”Error Message”
/`>
</code>
Instead of this...

`<auth>
  <status type="symbol">failed</status>
  <errorcode>UNKNOWN_LOGIN</errorcode>
  <errormessage>Invalid credentials.</errormessage>
</auth`>

Any help will be highly appreciated?

Claudio

**Comment by gregory** [comment]
hey @kdisneur  :) 
Have you been able to get some decent xml with rabl? The readme is selling the fact we can build xml and json with the the same dsl but sounds like there is a lot of issues in the list...

**Comment by kdisneur** [comment]
@gregory hey :)

To be honest I haven't tried to generate any XML, with `rabl`, for almost 2 years. So I don't how it handles that now. Sorry, I can't help much.
