### ISSUE TITLE
Rails 7 compatibility

### ISSUE THREAD

**Issue by SeanLF** [nesquena/rabl#749]
The following line needs to be changed to add support to Rails 7:
https://github.com/nesquena/rabl/blob/855040f082920a85b6ced9388959043bcd46faa2/lib/rabl/template.rb#L65-L66

Seems to be resolved with:

```ruby
# Rails 6.X Template 
 if defined?(ActionView) && defined?(Rails) && Rails::VERSION::MAJOR >= 6
```

(filing issue as rails 7 just reached rc1)

**Comment by tagliala** [comment]
Hi, there are also other points:

https://github.com/nesquena/rabl/blob/02b3464a6dfb27a4a34365303974604688d7eb2b/lib/rabl/railtie.rb#L25

https://github.com/nesquena/rabl/blob/04cb2961c46a922be266dcc9d9bbda7b13c778c1/lib/rabl/engine.rb#L396

https://github.com/nesquena/rabl/blob/02b3464a6dfb27a4a34365303974604688d7eb2b/lib/rabl.rb#L20-L22

We need to setup integration tests before doing this change. I can give a try during the weekend. PR are welcomed
