### ISSUE TITLE
Register with Rails 8 via an initializer (fix for ActionView::MissingTemplate)

### ISSUE THREAD

**Issue by rietta** [nesquena/rabl#770]
In one application, once upgraded to Rails 8, `.json.rabl` views stopped rendering. Looking at the error I noticed that rabl was not in the list of handlers in the ActionView::MissingTemplate exception:

```
     ActionView::MissingTemplate:
       Missing template activities/index, application/index with {:locale=>[:en], :formats=>[:json], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}.
```
Attempting to specifically call Rabl.register! did not fix it.

What did fix the issues is adding an an initializer with the following code:

```ruby
# For Rails 8 compatibility, specifically register the Rabl renderer with ActionView
# This is not documented anywhere on the Internet, not even the Rabl issues.
# ActionView::Template.register_template_handler :rabl, ActionView::Template::Handlers::Rabl

# In the Gem, this needs to be updated. The underlying issue is no configuration block applies to
# Rails 8, on line 66 of the version check only matches 6 or 7 with 
# `Rails.respond_to?(:version) && Rails.version.to_s =~ /^[67]/`
# See lib/rabl/template.rb

# This is a copy paste from the section for Rails 7 without the condition.

module ActionView
    module Template::Handlers
        class Rabl
            class_attribute :default_format
            self.default_format = :json

            def self.call(template, source)
                %{ ::Rabl::Engine.new(#{source.inspect}).
                    apply(self, assigns.merge(local_assigns)).
                    render }
            end # call
        end # rabl class
    end # handlers
end

ActionView::Template.register_template_handler :rabl, ActionView::Template::Handlers::Rabl
```

I am happy to open a pull request for documentation or to add code. But wanted to discuss this with others first. Have you seen this error in your Rails 8 applications using the latest rabl gem?

**Comment by rietta** [comment]
I edited the post with corrected code as my testing has continued. To avoid confusion from those coming to this later.

**Comment by tagliala** [comment]
Hello,

the version supporting Rails 8 has not been released yet, can you please try to use Rabl from master?

```
gem 'rabl', github: 'nesquena/rabl'
```

**Comment by nesquena** [comment]
If you confirm it works, we can push Rails 8 support into a gem, @tagliala I'll add you as an owner to the gem too

**Comment by tagliala** [comment]
> If you confirm it works, we can push Rails 8 support into a gem, @tagliala I'll add you as an owner to the gem too

I've run the integration tests locally and they pass. Let's ask to @basex for a real-life scenario and @rietta for a confirmation that the master branch works without extra configuration

> @tagliala I'll add you as an owner to the gem too

Thanks, so I can push just in case

**Comment by tagliala** [comment]
Thanks!

**Comment by rietta** [comment]
I have not yet looked at what exactly you changed in the master branch to make it compatible if it was just a version check change or something more.

**Comment by rietta** [comment]
Okay, just took a look at the changes in https://github.com/nesquena/rabl/commit/1117f237adce4462d14caf50a966848fd37e7d27. Super clean work! Thank you.

**Comment by basex** [comment]
I'm using Rails 8 in production with rabl (master branch version) for several days without issues.

**Comment by adamtao** [comment]
Likewise, the current master branch works perfectly in my rails 8 application.

**Comment by nesquena** [comment]
@tagliala I invited you as a maintainer for the gem. Would you feel comfortable cutting a new release? Maybe major version update?

Thanks to everyone for testing!

**Comment by tagliala** [comment]
> I invited you as a maintainer for the gem

Sorry I do not see the invitation, I can release a new version

> Maybe major version update?

Since this still supports Ruby < 1.8, I would leave the major release for another time

**Comment by nesquena** [comment]
Sounds good, I resent the invitation via rubygems, maybe check spam

@tagliala 
<img width="921" alt="image" src="https://github.com/user-attachments/assets/7f3c1126-537f-484f-a65a-4bc3de762fca">

**Comment by tagliala** [comment]
Thanks, now I got the email and I've verified. I will create 0.17.0 and release

**Comment by tagliala** [comment]
Sorry, I've now seen the previous invitation too, I've missed it yesterday
